### ISSUE TITLE
I having a problem with the wallet. I using the latest wallet. I was working fine. Since yesterday I am noticing this issue.  After launching the wallet I am not  able to view the wallet in the desktop.  However, I checked the task manager that showed the process is running. I rebooted that machine multiple times. Please advice if there is any solution.

### ISSUE THREAD

**Issue by hasanora** [reddcoin-project/reddcoin-3.10#167] opened 2020-09-03 15:12 UTC
I having a problem with the wallet. I using the latest wallet. I was working fine. Since yesterday I am noticing this issue.  After launching the wallet I am not able to view the wallet in the desktop.  However, I checked the task manager that showed the process is running. I rebooted that machine multiple times. Please advice if there is any solution.
Running on win10 pro
 
![reddcoin](https://user-images.githubusercontent.com/13524004/92133250-26535080-edd6-11ea-9e63-dd953fbc4435.png)

_Originally posted by @nasah3da1 in https://github.com/reddcoin-project/reddcoin/issues/138#issuecomment-686560237_

**Comment by reddink** [comment] 2020-09-04 07:47
Duplicate of #168

**Closed as completed** 2020-09-04 07:46 UTC
